version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - public
      - admin

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      PORT: 80
      DATABASE_HOST: postgresql
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      IMAGE_BASE: /data/images
    volumes:
      - server:/data
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
  server:
