version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
  
  ai:
    build:
      context: .
      dockerfile: ai.Dockerfile
    environment:
      SQL_USER: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_DB: ${POSTGRES_DB}
      SQL_HOST: "postgresql:5432"
    depends_on:
      - postgresql

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      PORT: 80
      DATABASE_HOST: postgresql
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}
      IMAGE_BASE: /data/images
      API_KEY: ${API_KEY}
    volumes:
      - server:/data
    depends_on:
      - ai
      - postgresql

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
  server:
