name: ai

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  merge_group:
    branches: [ main ]

jobs:
  ai-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install poetry & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry install -vv -C ./ai -n

    - name: Black formatting check
      run: |
        poetry run -C ./ai black --check --verbose ./ai

    - name: Pylint check
      run: |
        poetry run -C ./ai pylint $(git ls-files './ai/**/*.py')

    # - name: Mypy check
    #   env:
    #     MYPYPATH: ./server
    #   run: |
    #     echo y | poetry run -C ./ai mypy --install-types ./ai || true
    #     poetry run -C ./ai mypy --strict ./ai

    # - name: Pytest
    #   run: |
    #     poetry run -C ./ai pytest --cov=./ai --cov-report=xml ./ai

    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
