name: docker

on:
  push:
    branches: [ main ]

  merge_group:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  docker-build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Server Dockerfile
      run: docker build -f server.Dockerfile .
